# Generated by Django 4.1.3 on 2022-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('passport', models.CharField(max_length=20)),
            ],
        ),
    ]
