# Generated by Django 4.1.3 on 2022-12-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sportsman_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
