# Generated by Django 4.1.3 on 2022-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sportsman_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sportmen-images/', verbose_name='Изображение'),
        ),
    ]
