# Generated by Django 4.1.3 on 2022-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_anthropometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometry',
            name='index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
