# Generated by Django 4.1.3 on 2022-12-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_anthropometry_height_alter_anthropometry_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('sportman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportsman')),
            ],
        ),
    ]
