# Generated by Django 4.1.3 on 2022-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_competitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='anthropometry',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='anthropometry',
            name='index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometry',
            name='weight',
            field=models.FloatField(),
        ),
    ]
