# Generated by Django 4.1.3 on 2022-12-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_career_sportman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Подтягивания на перекладине (кол-во)', 'Подтягивания на перекладине (кол-во)'), ('Тройной прыжок с места (см)', 'Тройной прыжок с места (см)'), ('Пятикратный прыжок (см)', 'Пятикратный прыжок (см)'), ('Поднимание туловища 60 сек. (кол-во)', 'Поднимание туловища 60 сек. (кол-во)'), ('Бег 60м (сек)', 'Бег 60м (сек)'), ('Бег 300м (сек)', 'Бег 300м (сек)'), ('Бег 3000м (мин)', 'Бег 3000м (мин)'), ('Бег на коньках 36м лицом вперед (сек)', 'Бег на коньках 36м лицом вперед (сек)'), ('Бег на коньках 36м спиной вперед (сек)', 'Бег на коньках 36м спиной вперед (сек)'), ('Челночный бег на коньках 18 х 12 м (сек)', 'Челночный бег на коньках 18 х 12 м (сек)'), ('8-минутный бег на коньках (км)', '8-минутный бег на коньках (км)'), ('Точность бросков шайбы в цель (очки)', 'Точность бросков шайбы в цель (очки)')], default='Бег 60м (сек)', max_length=300)),
                ('result', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('sportman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportsman')),
            ],
        ),
    ]
