# Generated by Django 4.1.3 on 2022-12-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('arterial_pressure', models.CharField(blank=True, max_length=7, null=True)),
                ('medical_tests', models.FileField(blank=True, null=True, upload_to='')),
                ('medical_survey', models.FileField(blank=True, null=True, upload_to='')),
                ('time', models.DateField()),
                ('sportman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportsman')),
            ],
        ),
    ]
