# Generated by Django 4.1.3 on 2022-12-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proteins', models.CharField(max_length=10)),
                ('fats', models.CharField(max_length=10)),
                ('carbo', models.CharField(max_length=10)),
                ('calories', models.CharField(max_length=10)),
            ],
        ),
    ]
