# Generated by Django 4.1.3 on 2022-12-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbo',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(max_length=10),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_breakfast', models.TextField(blank=True, null=True)),
                ('monday_lunch', models.TextField(blank=True, null=True)),
                ('monday_dinner', models.TextField(blank=True, null=True)),
                ('monday_calories', models.TextField(blank=True, null=True)),
                ('tuesday_breakfast', models.TextField(blank=True, null=True)),
                ('tuesday_lunch', models.TextField(blank=True, null=True)),
                ('tuesday_dinner', models.TextField(blank=True, null=True)),
                ('tuesday_calories', models.TextField(blank=True, null=True)),
                ('wednesday_breakfast', models.TextField(blank=True, null=True)),
                ('wednesday_lunch', models.TextField(blank=True, null=True)),
                ('wednesday_dinner', models.TextField(blank=True, null=True)),
                ('wednesday_calories', models.TextField(blank=True, null=True)),
                ('thursday_breakfast', models.TextField(blank=True, null=True)),
                ('thursday_lunch', models.TextField(blank=True, null=True)),
                ('thursday_dinner', models.TextField(blank=True, null=True)),
                ('thursday_calories', models.TextField(blank=True, null=True)),
                ('friday_breakfast', models.TextField(blank=True, null=True)),
                ('friday_lunch', models.TextField(blank=True, null=True)),
                ('friday_dinner', models.TextField(blank=True, null=True)),
                ('friday_calories', models.TextField(blank=True, null=True)),
                ('saturday_breakfast', models.TextField(blank=True, null=True)),
                ('saturday_lunch', models.TextField(blank=True, null=True)),
                ('saturday_dinner', models.TextField(blank=True, null=True)),
                ('saturday_calories', models.TextField(blank=True, null=True)),
                ('sunday_breakfast', models.TextField(blank=True, null=True)),
                ('sunday_lunch', models.TextField(blank=True, null=True)),
                ('sunday_dinner', models.TextField(blank=True, null=True)),
                ('sunday_calories', models.TextField(blank=True, null=True)),
                ('sportman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportsman')),
            ],
        ),
    ]
