# Generated by Django 4.1.3 on 2022-12-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_trauma_alter_diet_friday_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trauma',
            name='sportman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportsman'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
